"""
Published test vectors for the primitives this protocol is built from.

Why this file exists
--------------------
``tests/test_primitives.py`` cross-validates against ``cryptography``, a second
implementation of the same standards. That catches disagreement between two
implementations, but it cannot catch a case where **both** are wrong the same
way, and it says nothing about conformance to a specification. Published
vectors do: they are a fixed external reference, so passing means agreeing with
the standard rather than with a sibling library.

What is *not* here, and why
---------------------------
There are no Signal test vectors for X3DH or the Double Ratchet, because Signal
does not publish any. Both specification documents were checked:

- X3DH, revision 1 (2016-11-04), https://signal.org/docs/specifications/x3dh/
- The Double Ratchet Algorithm, revision 4 (2025-11-04),
  https://signal.org/docs/specifications/doubleratchet/

Neither has a test-vectors appendix; both end at References. The composed
protocols therefore still rely on the cross-validation in
``tests/test_primitives.py`` and on round-trip tests, and that limitation is
real. The closest thing to an external reference for the compositions is the
pair of intermediate values asserted in
``TestComposedProtocolsBoundToThePrimitives`` below, which pins the X3DH root
key and the first ratchet step to the primitives checked here. It is a
self-consistency anchor, not a conformance claim.

Provenance of every constant below is the RFC section named in its comment.
Nothing in this file is generated by this implementation, and a failing
assertion means a transcription error or a real defect -- never a value to be
regenerated to make the suite green.
"""

import nacl.bindings
import pytest
from nacl.exceptions import BadSignatureError
from nacl.signing import SigningKey, VerifyKey

from src.crypto.kdf import expand, extract, hkdf
from src.crypto.key_management import (
    identity_private_x25519,
    identity_public_x25519,
)


def h(text: str) -> bytes:
    """Hex, tolerating the whitespace the RFCs use to group their output."""
    return bytes.fromhex(''.join(text.split()))


# ---------------------------------------------------------------------------
# RFC 5869, Appendix A -- HKDF with SHA-256
# ---------------------------------------------------------------------------
#
# Our kdf.py is a hand-written HKDF, so these are the highest-value vectors in
# the repository. They also cover the intermediate PRK, which the
# cross-validation could not: test_primitives only ever compared final output,
# so a broken extract step balanced out against a broken expand step would have
# gone unnoticed.

#: A.1, basic test case with SHA-256.
RFC5869_CASE_1 = {
    'ikm': h('0b' * 22),
    'salt': h('000102030405060708090a0b0c'),
    'info': h('f0f1f2f3f4f5f6f7f8f9'),
    'length': 42,
    'prk': h('077709362c2e32df0ddc3f0dc47bba63'
             '90b6c73bb50f9c3122ec844ad7c2b3e5'),
    'okm': h('3cb25f25faacd57a90434f64d0362f2a'
             '2d2d0a90cf1a5a4c5db02d56ecc4c5bf'
             '34007208d5b887185865'),
}

#: A.2, SHA-256 with longer inputs and outputs. L=82 needs three HMAC blocks,
#: so this is the vector that would catch an off-by-one in the block counter.
RFC5869_CASE_2 = {
    'ikm': h('000102030405060708090a0b0c0d0e0f'
             '101112131415161718191a1b1c1d1e1f'
             '202122232425262728292a2b2c2d2e2f'
             '303132333435363738393a3b3c3d3e3f'
             '404142434445464748494a4b4c4d4e4f'),
    'salt': h('606162636465666768696a6b6c6d6e6f'
              '707172737475767778797a7b7c7d7e7f'
              '808182838485868788898a8b8c8d8e8f'
              '909192939495969798999a9b9c9d9e9f'
              'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf'),
    'info': h('b0b1b2b3b4b5b6b7b8b9babbbcbdbebf'
              'c0c1c2c3c4c5c6c7c8c9cacbcccdcecf'
              'd0d1d2d3d4d5d6d7d8d9dadbdcdddedf'
              'e0e1e2e3e4e5e6e7e8e9eaebecedeeef'
              'f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff'),
    'length': 82,
    'prk': h('06a6b88c5853361a06104c9ceb35b45c'
             'ef760014904671014a193f40c15fc244'),
    'okm': h('b11e398dc80327a1c8e7f78c596a4934'
             '4f012eda2d4efad8a050cc4c19afa97c'
             '59045a99cac7827271cb41c65e590e09'
             'da3275600c2f09b8367793a9aca3db71'
             'cc30c58179ec3e87c14c01d5c1f3434f'
             '1d87'),
}

#: A.3, SHA-256 with zero-length salt *and* zero-length info. This is the
#: vector for the empty-salt special case in extract(): the RFC says an absent
#: salt is HashLen zero bytes, which is a rule an implementation can get wrong
#: in a way that still round-trips.
RFC5869_CASE_3 = {
    'ikm': h('0b' * 22),
    'salt': b'',
    'info': b'',
    'length': 42,
    'prk': h('19ef24a32c717b167f33a91d6f648bdf'
             '96596776afdb6377ac434c1c293ccb04'),
    'okm': h('8da4e775a563c18f715f802a063c5a31'
             'b8a11f5c5ee1879ec3454e5f3c738d2d'
             '9d201395faa4b61a96c8'),
}

RFC5869_CASES = [
    pytest.param(RFC5869_CASE_1, id='A.1-basic'),
    pytest.param(RFC5869_CASE_2, id='A.2-long'),
    pytest.param(RFC5869_CASE_3, id='A.3-zero-salt-and-info'),
]


class TestHkdfRfc5869:
    @pytest.mark.parametrize('case', RFC5869_CASES)
    def test_extract_matches_the_rfc_prk(self, case):
        """
        The intermediate value, which nothing checked before.

        extract() and expand() are separate functions here, so a bug in either
        could hide behind the other. The published PRK pins the split.
        """
        assert extract(case['salt'], case['ikm']) == case['prk']

    @pytest.mark.parametrize('case', RFC5869_CASES)
    def test_expand_matches_the_rfc_okm(self, case):
        assert expand(case['prk'], case['info'], case['length']) == case['okm']

    @pytest.mark.parametrize('case', RFC5869_CASES)
    def test_combined_matches_the_rfc_okm(self, case):
        assert hkdf(
            case['salt'], case['ikm'], case['info'], case['length']
        ) == case['okm']

    def test_absent_salt_matches_an_explicit_zero_salt(self):
        """
        RFC 5869 section 2.2: an absent salt is HashLen zero bytes.

        X3DH always passes an explicit zero salt, so it relies on the general
        path. A caller elsewhere must not get a different answer for omitting
        the salt, and must get the same PRK either way.
        """
        ikm, info = RFC5869_CASE_1['ikm'], RFC5869_CASE_1['info']
        assert extract(b'', ikm) == extract(b'\x00' * 32, ikm)
        assert hkdf(b'', ikm, info, 42) == hkdf(b'\x00' * 32, ikm, info, 42)

    def test_zero_salt_case_three_agrees_with_the_rfc(self):
        """
        A.3 explicitly, stated as its own case.

        ``test_extract_matches_the_rfc_prk`` already covers it, but that one
        could in principle be satisfied by extract() treating an empty salt as
        an empty HMAC key rather than as 32 zero bytes. RFC 5869 A.3 is the
        vector that distinguishes those, so it is worth naming.
        """
        assert extract(b'', RFC5869_CASE_3['ikm']) == RFC5869_CASE_3['prk']
        assert (
            expand(RFC5869_CASE_3['prk'], b'', 42) == RFC5869_CASE_3['okm']
        )

    def test_maximum_output_length(self):
        """
        RFC 5869 section 2.3: L <= 255*HashLen. The 255-block boundary is an
        explicit limit in expand() and is tested at the edge.
        """
        prk = RFC5869_CASE_1['prk']
        info = RFC5869_CASE_1['info']
        assert len(expand(prk, info, 255 * 32)) == 255 * 32
        with pytest.raises(ValueError):
            expand(prk, info, 255 * 32 + 1)


# ---------------------------------------------------------------------------
# RFC 7748, section 5.2 -- X25519
# ---------------------------------------------------------------------------
#
# Every DH in X3DH and in both ratchets is X25519, so this is the vector that
# covers the primitive the whole protocol's forward secrecy rests on.

#: 5.2, X25519, first vector.
RFC7748_X25519_1 = (
    'a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4',
    'e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c',
    'c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552',
)

#: 5.2, X25519, second vector.
RFC7748_X25519_2 = (
    '4b66e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba0d',
    'e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a493',
    '95cbde9476e8907d7aade45cb4b873f88b595a68799fa152e6f8f7647aac7957',
)

#: 5.2, the iterated form: k and u both start at 09 followed by 31 zero bytes,
#: and each iteration sets k to f(k) and u to the old k.
RFC7748_ITERATED_SEED = h('09' + '00' * 31)
RFC7748_ITERATED_1 = h(
    '422c8e7a6227d7bca1350b3e2bb7279f7897b87bb6854b783c60e80311ae3079'
)
RFC7748_ITERATED_1000 = h(
    '684cf59ba83309552800ef566f2f4d3c1c3887c49360e3875f2eb94d99532c51'
)
RFC7748_ITERATED_1000000 = h(
    '7c3911e0ab2586fd864497297e575e6f3bc601c0883c30df5f4dd2d24f665424'
)


def _x25519(scalar: bytes, u_coordinate: bytes) -> bytes:
    """
    The bare RFC 7748 function, with no low-order rejection.

    Deliberately ``crypto_scalarmult`` directly rather than the project's
    ``_dh``, because the wrappers add an all-zero check that these vectors do
    not exercise. This checks the primitive; the wrapper's rejection behaviour
    is checked in test_double_ratchet.py and test_x3dh.py.
    """
    return nacl.bindings.crypto_scalarmult(scalar, u_coordinate)


class TestX25519Rfc7748:
    @pytest.mark.parametrize('vector', [RFC7748_X25519_1, RFC7748_X25519_2],
                             ids=['first', 'second'])
    def test_scalarmult_matches_the_rfc(self, vector):
        scalar, u_coordinate, expected = (h(part) for part in vector)
        assert _x25519(scalar, u_coordinate) == expected

    @pytest.mark.parametrize('iterations, expected', [
        (1, RFC7748_ITERATED_1),
        (1000, RFC7748_ITERATED_1000),
    ], ids=['1-iteration', '1000-iterations'])
    def test_iterated_matches_the_rfc(self, iterations, expected):
        """
        The iterated vectors catch a wrong clamping or a non-X25519 ladder.

        A single-shot vector can pass with an implementation that is subtly
        wrong in a way only repetition exposes. The 1,000,000-iteration vector
        is omitted deliberately: it costs minutes of CI time to re-derive a
        property the 1,000-iteration case already covers.
        """
        k = u_coordinate = RFC7748_ITERATED_SEED
        for _ in range(iterations):
            k, u_coordinate = _x25519(k, u_coordinate), k
        assert k == expected

    def test_diffie_hellman_is_symmetric(self):
        """
        Both parties must reach the same secret.

        The symmetry is ``f(a, base(b)) == f(b, base(a))`` -- the two inputs
        are a private scalar and the *other* party's public key. It is not
        ``f(a, b) == f(b, a)``: swapping the arguments of a single call is a
        different computation, not a reordered one, and libsodium is right to
        return different values for it.

        X3DH and both ratchets rely on this in every DH they perform, and a
        backend that broke it would pass the one-shot vectors above, which only
        ever check one direction.
        """
        secret_a = h(RFC7748_X25519_1[0])
        secret_b = h(RFC7748_X25519_2[0])

        public_b = nacl.bindings.crypto_scalarmult_base(secret_b)
        public_a = nacl.bindings.crypto_scalarmult_base(secret_a)

        assert _x25519(secret_a, public_b) == _x25519(secret_b, public_a)

    def test_the_million_iteration_value_is_recorded(self):
        """
        The vector is kept in the file even though it is not run.

        Deleting it would lose the reference; keeping it documents the choice
        above. Guarded on the value so an accidental edit is caught.
        """
        assert RFC7748_ITERATED_1000000.hex().startswith('7c3911e0ab2586fd')
        assert len(RFC7748_ITERATED_1000000) == 32


# ---------------------------------------------------------------------------
# RFC 8032, section 7.1 -- Ed25519
# ---------------------------------------------------------------------------
#
# Ed25519 authenticates the prekey bundle and the initiator's handshake. If
# signing or verification were wrong, X3DH would either reject honest peers or
# accept forged ones; test_x3dh_mitm.py covers the latter, but only against
# this same implementation's idea of Ed25519.

#: 7.1 TEST 1 -- empty message.
RFC8032_TEST_1 = {
    'secret': h('9d61b19deffd5a60ba844af492ec2cc4'
                '4449c5697b326919703bac031cae7f60'),
    'public': h('d75a980182b10ab7d54bfed3c964073a'
                '0ee172f3daa62325af021a68f707511a'),
    'message': b'',
    'signature': h('e5564300c360ac729086e2cc806e828a'
                   '84877f1eb8e5d974d873e06522490155'
                   '5fb8821590a33bacc61e39701cf9b46b'
                   'd25bf5f0595bbe24655141438e7a100b'),
}

#: 7.1 TEST 2 -- one byte, 0x72.
RFC8032_TEST_2 = {
    'secret': h('4ccd089b28ff96da9db6c346ec114e0f'
                '5b8a319f35aba624da8cf6ed4fb8a6fb'),
    'public': h('3d4017c3e843895a92b70aa74d1b7ebc'
                '9c982ccf2ec4968cc0cd55f12af4660c'),
    'message': h('72'),
    'signature': h('92a009a9f0d4cab8720e820b5f642540'
                   'a2b27b5416503f8fb3762223ebdb69da'
                   '085ac1e43e15996e458f3613d0f11d8c'
                   '387b2eaeb4302aeeb00d291612bb0c00'),
}

#: 7.1 TEST 3 -- two bytes, 0xaf82.
RFC8032_TEST_3 = {
    'secret': h('c5aa8df43f9f837bedb7442f31dcb7b1'
                '66d38535076f094b85ce3a2e0b4458f7'),
    'public': h('fc51cd8e6218a1a38da47ed00230f058'
                '0816ed13ba3303ac5deb911548908025'),
    'message': h('af82'),
    'signature': h('6291d657deec24024827e69c3abe01a3'
                   '0ce548a284743a445e3680d7db5ac3ac'
                   '18ff9b538d16f290ae67f760984dc659'
                   '4a7c15e9716ed28dc027beceea1ec40a'),
}

#: 7.1 TEST SHA(abc) -- 64 bytes, the standard abc test.
RFC8032_TEST_SHA_ABC = {
    'secret': h('833fe62409237b9d62ec77587520911e'
                '9a759cec1d19755b7da901b96dca3d42'),
    'public': h('ec172b93ad5e563bf4932c70e1245034'
                'c35467ef2efd4d64ebf819683467e2bf'),
    'message': h('ddaf35a193617abacc417349ae204131'
                 '12e6fa4e89a97ea20a9eeee64b55d39a'
                 '2192992a274fc1a836ba3c23a3feebbd'
                 '454d4423643ce80e2a9ac94fa54ca49f'),
    'signature': h('dc2a4459e7369633a52b1bf277839a00'
                   '201009a3efbf3ecb69bea2186c26b589'
                   '09351fc9ac90b3ecfdfbc7c66431e030'
                   '3dca179c138ac17ad9bef1177331a704'),
}

RFC8032_CASES = [
    pytest.param(RFC8032_TEST_1, id='TEST-1-empty-message'),
    pytest.param(RFC8032_TEST_2, id='TEST-2-one-byte'),
    pytest.param(RFC8032_TEST_3, id='TEST-3-two-bytes'),
    pytest.param(RFC8032_TEST_SHA_ABC, id='TEST-SHA-abc'),
]


class TestEd25519Rfc8032:
    @pytest.mark.parametrize('case', RFC8032_CASES)
    def test_public_key_derivation_matches_the_rfc(self, case):
        assert bytes(SigningKey(case['secret']).verify_key) == case['public']

    @pytest.mark.parametrize('case', RFC8032_CASES)
    def test_signature_matches_the_rfc(self, case):
        """
        Byte-for-byte, not merely valid.

        Ed25519 is deterministic, so the RFC fixes the exact signature. Anything
        that verifies but differs -- a different hash, a prehash variant, a
        randomised nonce -- is a different scheme, and X3DH's transcript
        signatures would not match what a peer computes.
        """
        signed = SigningKey(case['secret']).sign(case['message'])
        assert signed.signature == case['signature']

    @pytest.mark.parametrize('case', RFC8032_CASES)
    def test_the_rfc_signature_verifies(self, case):
        VerifyKey(case['public']).verify(case['message'], case['signature'])

    def test_a_tampered_signature_is_rejected(self):
        """
        The published vectors only show that valid signatures verify. This
        shows the check can fail, which is the property X3DH depends on when it
        refuses a substituted signed prekey.
        """
        tampered = bytearray(RFC8032_TEST_2['signature'])
        tampered[0] ^= 0x01
        with pytest.raises(BadSignatureError):
            VerifyKey(RFC8032_TEST_2['public']).verify(
                RFC8032_TEST_2['message'], bytes(tampered)
            )


# ---------------------------------------------------------------------------
# The one deviation with no published vector
# ---------------------------------------------------------------------------
#
# This project reuses an Ed25519 identity key for X25519 key agreement, which
# the Signal specification does not do and for which no RFC publishes a test
# vector. The conversion is libsodium's, so it cannot be checked against an
# external reference. What can be checked is the property the protocol
# actually needs from it: both parties must arrive at the same X25519 secret,
# and the public halves must correspond to the private halves. A break in any
# of that would silently break DH1 and DH2 in X3DH.

class TestEd25519ToX25519Conversion:
    def test_private_and_public_halves_agree(self):
        """
        The converted private key must produce the converted public key.

        If these two functions were derived from different definitions of the
        birational map, every handshake would compute DH1 and DH2 with a key
        the other side did not use.
        """
        for seed in (RFC8032_TEST_1, RFC8032_TEST_2, RFC8032_TEST_3,
                     RFC8032_TEST_SHA_ABC):
            signing_key = SigningKey(seed['secret'])
            private = identity_private_x25519(signing_key)
            derived = identity_public_x25519(signing_key.verify_key)
            assert bytes(private.public_key) == bytes(derived)

    def test_both_sides_reach_the_same_shared_secret(self):
        """
        The property X3DH depends on, end to end.

        DH1 = DH(IK_A, SPK_B) has to come out the same whether it is computed
        from Alice's converted private key and Bob's converted public key or
        the other way round. This is the check that would catch an inconsistent
        conversion; it is a self-consistency anchor, not a published vector.
        """
        alice = SigningKey(RFC8032_TEST_1['secret'])
        bob = SigningKey(RFC8032_TEST_2['secret'])

        alice_private = identity_private_x25519(alice)
        bob_private = identity_private_x25519(bob)
        alice_public = identity_public_x25519(alice.verify_key)
        bob_public = identity_public_x25519(bob.verify_key)

        forward = _x25519(
            bytes(alice_private), bytes(bob_public)
        )
        backward = _x25519(
            bytes(bob_private), bytes(alice_public)
        )
        assert forward == backward
        assert forward != b'\x00' * 32


# ---------------------------------------------------------------------------
# Composed protocols
# ---------------------------------------------------------------------------
#
# No published vectors exist for these, see the module docstring. What is
# asserted here is that the compositions reduce to the primitives above: the
# X3DH root key is exactly the HKDF construction RFC 5869 describes, fed the
# 0xFF-prefixed DH outputs, and the first ratchet step is exactly the KDF_RK
# the Double Ratchet specification defines. If someone changes a constant in
# either, these fail even though the round-trip tests would still pass, because
# both sides would change together.

class TestComposedProtocolsBoundToThePrimitives:
    def test_x3dh_root_key_is_the_documented_hkdf_construction(self):
        """
        SK = KDF(F || DH1 || ... || DH4), F = 0xFF * 32, salt = 32 zero bytes.

        X3DH section 2.2 and 3.3. Asserted against ``hkdf`` from this
        repository rather than against ``cryptography``, so the X3DH composition
        is pinned to the implementation of HKDF that RFC 5869's own vectors
        validate above.
        """
        from src.crypto.x3dh import X3DH, X25519_F

        dh_parts = [
            RFC7748_X25519_1_EXPECTED,
            RFC7748_X25519_2_EXPECTED,
            RFC8032_TEST_3['public'],
            RFC8032_TEST_1['public'],
        ]
        # The DH outputs are 32 bytes each and are only checkable as a set of
        # correctly sized values here; the actual DH is covered by the X25519
        # vectors above and by test_x3dh.py.
        for part in dh_parts:
            assert len(part) == 32

        context = b'DecentralizedMessenger-X3DH-v1'
        ours = X3DH.derive_master_key(dh_parts, context=context)
        expected = hkdf(
            salt=b'\x00' * 32,
            ikm=X25519_F + b''.join(dh_parts),
            info=context,
            length=32,
        )
        assert ours == expected

    def test_ratchet_root_key_step_is_hkdf_over_the_dh_output(self):
        """
        KDF_RK(rk, dh_out) = HKDF(salt=rk, ikm=dh_out, info=..., 64 bytes),
        split into a new root key and a new chain key.

        The Double Ratchet specification, section 3.1. The first half is the
        root key and the second the chain key, which is the detail an
        off-by-one gets wrong in a way that still round-trips.
        """
        from src.crypto.double_ratchet import DoubleRatchet, HKDF_INFO, KEY_SIZE

        ratchet = DoubleRatchet.__new__(DoubleRatchet)
        root_key = RFC5869_CASE_1['prk']
        dh_output = RFC7748_X25519_1_EXPECTED

        new_root, new_chain = ratchet._kdf_rk(root_key, dh_output)
        expected = hkdf(
            salt=root_key,
            ikm=dh_output,
            info=HKDF_INFO + b'\x01',
            length=2 * KEY_SIZE,
        )
        assert new_root + new_chain == expected
        assert new_root == expected[:KEY_SIZE]
        assert new_chain == expected[KEY_SIZE:]

    def test_kdf_ck_constants_are_in_specification_order(self):
        """
        KDF_CK(ck) = (HMAC(ck, 0x01), HMAC(ck, 0x02)), next chain key first.

        The Double Ratchet specification, section 3.1, fixes both the constants
        and which is which. The original code had them the other way round, and
        that defect was invisible to every round-trip test because both sides
        were wrong together -- it only surfaced as incompatibility with
        libsignal. Pinning the order here is what stops it recurring.
        """
        import hashlib
        import hmac

        from src.crypto.double_ratchet import DoubleRatchet

        ratchet = DoubleRatchet.__new__(DoubleRatchet)
        chain_key = RFC5869_CASE_1['prk']

        next_chain_key, message_key = ratchet._kdf_ck(chain_key)
        assert next_chain_key == hmac.new(
            chain_key, b'\x01', hashlib.sha256
        ).digest()
        assert message_key == hmac.new(
            chain_key, b'\x02', hashlib.sha256
        ).digest()
        assert next_chain_key != message_key


# ---------------------------------------------------------------------------
# Protocol constants
# ---------------------------------------------------------------------------
#
# The values below are part of the wire and session contract, not internal
# tuning. They are pinned as literals on purpose: deriving the expected value
# from the module under test would make the assertion true for any edit, which
# is how a change to the HKDF info string can pass every test while breaking
# every stored session.
#
# PROTOCOL_VERSION exists precisely because these strings changed once already.
# The v2 bump came with a different KDF_CK and a different HKDF info string, and
# sessions written before it are refused on load. Changing one of these without
# bumping the version reintroduces the exact failure the version check was added
# to prevent: sessions that load cleanly and then silently fail to decrypt.

class TestProtocolConstantsArePinned:
    def test_ratchet_hkdf_info(self):
        from src.crypto.double_ratchet import HKDF_INFO
        assert HKDF_INFO == b'WhisperRatchet-v2'

    def test_ratchet_protocol_version(self):
        from src.crypto.double_ratchet import PROTOCOL_VERSION
        assert PROTOCOL_VERSION == 2

    def test_x3dh_context(self):
        """
        Mixed in as the HKDF info for the X3DH root key.

        The specification leaves info empty. A non-empty context is deliberate
        domain separation and is a documented deviation, but it is also a
        constant both sides must agree on.
        """
        from src.crypto.x3dh import DEFAULT_CONTEXT
        assert DEFAULT_CONTEXT == b'DecentralizedMessenger-X3DH-v1'

    def test_x3dh_domain_separator_prefix(self):
        """
        F = 0xFF * 32 for 256-bit curves, X3DH section 4.

        This is specified, not chosen, so it is a conformance value.
        """
        from src.crypto.x3dh import X25519_F
        assert X25519_F == b'\xff' * 32

    def test_initiator_transcript_label(self):
        from src.crypto.x3dh import INIT_TRANSCRIPT_LABEL
        assert INIT_TRANSCRIPT_LABEL == b'X3DH-init-v1'

    def test_key_confirmation_info(self):
        from src.crypto.x3dh import KEY_CONFIRMATION_INFO
        assert KEY_CONFIRMATION_INFO == b'WhisperKeyConfirmation'

    def test_x3dh_default_context_is_used_when_none_is_given(self):
        """
        The previous test pins the string; this pins that it is the default.

        A caller that omits the context and one that passes it explicitly must
        derive the same root key, or two code paths silently produce different
        sessions.
        """
        from src.crypto.x3dh import DEFAULT_CONTEXT, X3DH

        parts = [RFC5869_CASE_1['prk']] * 4
        assert (
            X3DH.derive_master_key(parts)
            == X3DH.derive_master_key(parts, context=DEFAULT_CONTEXT)
        )
        assert (
            X3DH.derive_master_key(parts)
            != X3DH.derive_master_key(parts, context=b'something else')
        )


#: Outputs from the RFC 7748 vectors, reused above as arbitrary 32-byte secrets.
RFC7748_X25519_1_EXPECTED = h(RFC7748_X25519_1[2])
RFC7748_X25519_2_EXPECTED = h(RFC7748_X25519_2[2])
