"""
Regression tests for X3DH authentication.

The vulnerability these tests exist for: ``initiate_handshake`` used to accept
a prekey bundle without ever checking ``signed_prekey_signature``. An active
attacker could keep the genuine identity key but swap the signed prekey, and
both sides would derive a shared secret the attacker also knows. The signature
is generated by the responder but was never verified by anybody.

Each test here fails against the unfixed code and passes against the fix.
"""

import pytest
from nacl.public import PrivateKey
from nacl.signing import SigningKey

from src.crypto.prekey_store import (
    InMemoryPreKeyStore,
    OneTimePreKeyAlreadyUsed,
)
from src.crypto.x3dh import (
    X3DH,
    HandshakeInit,
    InvalidHandshakeError,
    InvalidSignatureError,
    PreKeyBundle,
    X3DHResponder,
)


def make_responder(prekey_count=3):
    """Build a responder with a signed prekey and a pool of one-time prekeys."""
    x3dh = X3DH()
    identity_private, identity_public = x3dh.generate_identity_keys()
    spk_private, spk_public, spk_signature = x3dh.generate_signed_prekey(
        identity_private
    )
    store = InMemoryPreKeyStore()
    for index in range(prekey_count):
        store.put(x3dh.generate_one_time_prekey(key_id=1000 + index))
    responder = X3DHResponder(
        identity_private=identity_private,
        signed_prekey_private=spk_private,
        prekey_store=store,
    )
    return x3dh, responder, store, identity_public


def make_initiator():
    x3dh = X3DH()
    identity_private, identity_public = x3dh.generate_identity_keys()
    return x3dh, identity_private, identity_public


def replace(structure, **changes) -> HandshakeInit:
    """Copy a frozen dataclass with some fields replaced."""
    values = {
        'identity_key': structure.identity_key,
        'identity_key_x25519': structure.identity_key_x25519,
        'ephemeral_key': structure.ephemeral_key,
        'signature': structure.signature,
        'one_time_prekey_id': structure.one_time_prekey_id,
    }
    values.update(changes)
    return HandshakeInit(**values)


class TestBundleAuthentication:
    """The initiator must authenticate the bundle before using it."""

    def test_honest_bundle_verifies(self):
        _, responder, _, _ = make_responder()
        X3DH.verify_bundle(responder.publish_bundle())

    def test_substituted_signed_prekey_is_rejected(self):
        """
        The core regression.

        The attacker keeps the genuine identity key and the genuine signature
        bytes, and only replaces the signed prekey. Verification must fail.
        """
        x3dh, responder, _, identity_public = make_responder()
        honest = responder.publish_bundle()

        attacker_spk = PrivateKey.generate().public_key
        tampered = PreKeyBundle(
            identity_key=identity_public,
            signed_prekey=attacker_spk,
            signed_prekey_signature=honest.signed_prekey_signature,
        )

        with pytest.raises(InvalidSignatureError):
            x3dh.verify_bundle(tampered)

    def test_handshake_aborts_on_substituted_signed_prekey(self):
        x3dh, responder, _, _ = make_responder()
        honest = responder.publish_bundle()
        _, alice_private, _ = make_initiator()

        tampered = PreKeyBundle(
            identity_key=honest.identity_key,
            signed_prekey=PrivateKey.generate().public_key,
            signed_prekey_signature=honest.signed_prekey_signature,
        )

        with pytest.raises(InvalidSignatureError):
            x3dh.initiate_handshake(alice_private, tampered)

    def test_substitution_lets_attacker_derive_the_secret(self):
        """
        Demonstrates the impact, and that the fix blocks it.

        If the signature check is skipped, the attacker's own prekey produces
        exactly the key Alice derives, so the attacker reads the session. With
        the check in place the handshake is refused before any DH is computed.
        """
        x3dh, responder, _, _ = make_responder()
        honest = responder.publish_bundle()
        _, alice_private, _ = make_initiator()

        attacker_spk_private = PrivateKey.generate()
        tampered = PreKeyBundle(
            identity_key=honest.identity_key,
            signed_prekey=attacker_spk_private.public_key,
            signed_prekey_signature=honest.signed_prekey_signature,
        )

        # What Alice *would* have derived had the bundle not been authenticated.
        alice_ephemeral = PrivateKey.generate()
        alice_parts = x3dh._initiator_dh_parts(
            alice_private, alice_ephemeral, tampered
        )

        # What the attacker derives from the same wire data.
        from src.crypto.key_management import (
            identity_private_x25519,
            identity_public_x25519,
        )
        alice_ik_x = identity_private_x25519(alice_private).public_key
        attacker_parts = (
            x3dh._dh(attacker_spk_private, alice_ik_x),
            x3dh._dh(alice_ephemeral, identity_public_x25519(honest.identity_key)),
            x3dh._dh(alice_ephemeral, attacker_spk_private.public_key),
        )
        assert x3dh.derive_master_key(alice_parts) == \
            x3dh.derive_master_key(attacker_parts), (
            'test is not demonstrating the attack: keys differ'
        )

        # And the fixed code refuses the very same bundle.
        with pytest.raises(InvalidSignatureError):
            x3dh.initiate_handshake(alice_private, tampered)

    def test_resigned_by_attacker_is_rejected(self):
        """Re-signing with the attacker's own key does not help either."""
        x3dh, responder, _, _ = make_responder()
        honest = responder.publish_bundle()
        _, alice_private, _ = make_initiator()

        attacker_signing = SigningKey.generate()
        attacker_spk = PrivateKey.generate().public_key
        forged = PreKeyBundle(
            identity_key=honest.identity_key,          # still Bob's real key
            signed_prekey=attacker_spk,
            signed_prekey_signature=attacker_signing.sign(
                attacker_spk.encode()
            ).signature,
        )

        with pytest.raises(InvalidSignatureError):
            x3dh.initiate_handshake(alice_private, forged)

    def test_corrupted_signature_is_rejected(self):
        x3dh, responder, _, _ = make_responder()
        honest = responder.publish_bundle()
        broken = bytes([honest.signed_prekey_signature[0] ^ 0xFF]) + \
            honest.signed_prekey_signature[1:]
        tampered = PreKeyBundle(
            identity_key=honest.identity_key,
            signed_prekey=honest.signed_prekey,
            signed_prekey_signature=broken,
        )
        with pytest.raises(InvalidSignatureError):
            x3dh.verify_bundle(tampered)

    def test_short_signature_is_rejected(self):
        x3dh, responder, _, _ = make_responder()
        honest = responder.publish_bundle()
        with pytest.raises(InvalidSignatureError):
            x3dh.verify_bundle(
                PreKeyBundle(
                    identity_key=honest.identity_key,
                    signed_prekey=honest.signed_prekey,
                    signed_prekey_signature=honest.signed_prekey_signature[:32],
                )
            )

    def test_bundle_validation_rejects_mismatched_prekey_fields(self):
        with pytest.raises(InvalidHandshakeError):
            PreKeyBundle(
                identity_key=make_responder()[3],
                signed_prekey=PrivateKey.generate().public_key,
                signed_prekey_signature=b'\x00' * 64,
                one_time_prekey=PrivateKey.generate().public_key,
                one_time_prekey_id=None,  # id without the key
            )


class TestInitiatorAuthentication:
    """The responder must authenticate the initiator's handshake message."""

    def test_honest_handshake_accepted(self):
        x3dh, responder, _, _ = make_responder()
        _, alice_private, _ = make_initiator()
        _, init = x3dh.initiate_handshake(alice_private, responder.publish_bundle())
        assert responder.handle_init(init) is not None

    def test_responder_rejects_swapped_ephemeral_key(self):
        """
        An attacker who relays a handshake but replaces the ephemeral key to
        read the reply must be caught: the swap breaks the transcript signature.
        """
        x3dh, responder, _, _ = make_responder()
        _, alice_private, _ = make_initiator()
        _, init = x3dh.initiate_handshake(alice_private, responder.publish_bundle())

        tampered = replace(init, ephemeral_key=PrivateKey.generate().public_key)
        with pytest.raises(InvalidSignatureError):
            responder.handle_init(tampered)

    def test_responder_rejects_foreign_identity_key(self):
        """Claiming someone else's identity key does not verify."""
        x3dh, responder, _, _ = make_responder()
        _, alice_private, alice_public = make_initiator()
        _, init = x3dh.initiate_handshake(alice_private, responder.publish_bundle())

        mallory_private, mallory_public = x3dh.generate_identity_keys()
        from src.crypto.key_management import identity_public_x25519
        tampered = replace(
            init,
            identity_key=mallory_public,
            identity_key_x25519=identity_public_x25519(mallory_public),
        )
        with pytest.raises(InvalidSignatureError):
            responder.handle_init(tampered)

    def test_responder_rejects_inconsistent_x25519_identity(self):
        """A valid signature over a mismatched conversion is still refused."""
        x3dh, responder, _, _ = make_responder()
        _, alice_private, _ = make_initiator()
        _, init = x3dh.initiate_handshake(alice_private, responder.publish_bundle())

        _, other_public = x3dh.generate_identity_keys()
        from src.crypto.key_management import identity_public_x25519
        tampered = replace(
            init, identity_key_x25519=identity_public_x25519(other_public)
        )
        with pytest.raises(InvalidSignatureError):
            responder.handle_init(tampered)

    def test_associated_data_must_match(self):
        x3dh, responder, _, _ = make_responder()
        _, alice_private, _ = make_initiator()
        _, init = x3dh.initiate_handshake(
            alice_private, responder.publish_bundle(), associated_data=b'ctx-a'
        )
        with pytest.raises(InvalidSignatureError):
            responder.handle_init(init, associated_data=b'ctx-b')

    def test_responder_rejects_unsigned_handshake(self):
        x3dh, responder, _, _ = make_responder()
        alice_private, alice_public = x3dh.generate_identity_keys()
        from src.crypto.key_management import identity_public_x25519
        forged = HandshakeInit(
            identity_key=alice_public,
            identity_key_x25519=identity_public_x25519(alice_public),
            ephemeral_key=PrivateKey.generate().public_key,
            signature=b'\x00' * 64,
        )
        with pytest.raises(InvalidSignatureError):
            responder.handle_init(forged)

    def test_responder_rejects_plain_object(self):
        """The old API accepted a bare public key; that path is gone."""
        x3dh, responder, _, _ = make_responder()
        with pytest.raises(InvalidHandshakeError):
            responder.handle_init('not-a-handshake')  # type: ignore[arg-type]


class TestOneTimePreKeyEnforcement:
    def test_forged_handshake_does_not_spend_a_prekey(self):
        """
        A forged handshake must not consume a prekey.

        Consuming before authenticating would let anyone drain the pool with
        junk handshakes, leaving the responder unable to establish any session
        with forward secrecy.
        """
        x3dh, responder, store, _ = make_responder(prekey_count=3)
        _, alice_private, _ = make_initiator()
        _, init = x3dh.initiate_handshake(alice_private, responder.publish_bundle())
        before = store.count()

        forged = replace(init, ephemeral_key=PrivateKey.generate().public_key)
        with pytest.raises(InvalidSignatureError):
            responder.handle_init(forged)

        assert store.count() == before
        assert not store.was_consumed(init.one_time_prekey_id)

    def test_replayed_init_cannot_reuse_a_one_time_prekey(self):
        x3dh, responder, store, _ = make_responder(prekey_count=2)
        _, alice_private, _ = make_initiator()
        _, init = x3dh.initiate_handshake(alice_private, responder.publish_bundle())

        responder.handle_init(init)
        assert store.count() == 1

        # Replaying the same handshake must not reuse the prekey: accepting it
        # would destroy forward secrecy.
        with pytest.raises(OneTimePreKeyAlreadyUsed):
            responder.handle_init(init)

    def test_replay_also_rejected_on_receive_handshake_path(self):
        """Consumption is enforced even when the caller drives the low-level API."""
        x3dh, responder, store, _ = make_responder(prekey_count=1)
        _, alice_private, _ = make_initiator()
        _, init = x3dh.initiate_handshake(alice_private, responder.publish_bundle())

        responder.handle_init(init)
        with pytest.raises(OneTimePreKeyAlreadyUsed):
            responder.handle_init(init)
        assert store.count() == 0
